### ISSUE TITLE
Versioning vs postgresql-migrations

### ISSUE THREAD

**Issue by NotBrianZach** [purcell/postgresql-migrations#4]
sorry if this isn't an appropriate place, but I was just wondering how this compares to 

https://gitlab.com/depesz/Versioning

seems like semi similar concept except versioning seems to expect you to either call each of the relevant scripts yourself or write some kind of tool to do so? And also keeps track of dependencies between migrations - this doesn't seem to do that? I guess in practice you copy the migrations sql in this project into beginning of every migration file? do you keep a separate folder that has rollbacks? (but I don't see code in this repo that deletes from the applied_migrations table)

**Comment by NotBrianZach** [comment]
had a conversation w/gpt4 about this

https://chat.openai.com/share/7efbd567-cfaf-40c5-997a-7ceb1edeac37

**Comment by purcell** [comment]
Thanks for asking! Yes, this file forms the basis of an ongoing migrations file in a project, so it gets copied in and then later extended. Simple and has been effective in practice.

I don't do rollback migrations at all — I don't really believe in them for various reasons, including that they rarely get tested, down/up migration pairs often aren't idempotent etc., and are also not usually the best way of resolving bad deploys.

I haven't looked at Versioning at all, but depesz knows his stuff, so I imagine it's good. There are many other more featureful migration tools around, e.g. sqitch, and the one in this repo has much more modest/minimal goals.
